create table Actor
(
    id int generated by default as identity PRIMARY KEY,
    name     varchar not null,
    age      int check (age > 0)
);

create table Movie
(
    id int generated by default as identity PRIMARY KEY,
    name     varchar(200) not null,
    year_of_production  int check (Movie.year_of_production > 1900)
);

-- join table

create table Actor_Movie(
                            actor_id int references Actor(id),
                            movie_id int references Movie(id),
                            primary key(actor_id, movie_id)
)
