-- drop table actor, movie, actor_movie;

create table Person
(
    id   int generated by default as identity PRIMARY KEY,
    name varchar not null,
    age  int check (age > 0)
);

create table Item
(
    id   int generated by default as identity PRIMARY KEY,
    person_id int references Person(id),
    item_name varchar not null
);

insert into Person(name, age)  values ('Aydar', 23);
insert into Item(person_id, item_name)  values (1, 'Airpods');
insert into Item(person_id, item_name)  values (1, 'Book');
insert into Item(person_id, item_name)  values (1, 'Laptop');